export default function HomePage() {
  return (
    <div
      className="w-full min-h-screen bg-cover bg-center bg-no-repeat p-6"
      style={{ backgroundImage: "url('/rm373batch4-07.jpg')" }}
    >
      <div className="backdrop-blur-[1px] bg-black/20 p-4 rounded-xl text-white">
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate distinctio repudiandae quas debitis fugiat a magni quibusdam dolore quidem optio, quis necessitatibus nesciunt beatae sequi? Corporis natus placeat cupiditate aliquid!
      Architecto autem, perferendis incidunt tenetur ipsa, minima sunt enim reiciendis laborum harum inventore aliquam asperiores id? Officiis illo commodi maiores consequatur magni adipisci, pariatur aliquam cum nobis iusto nulla dicta!
      Voluptatem similique aliquid dolore quo? Voluptatem doloribus in voluptas placeat eaque quidem praesentium? Quos, illum, enim ipsa impedit delectus nesciunt atque ad vitae esse tempore est. Accusantium quasi quidem delectus.
      Explicabo odio, amet, nemo voluptatem pariatur architecto alias facere suscipit sit, dicta mollitia? Minus distinctio maiores nulla? Libero quaerat voluptatem praesentium ea aspernatur, sit modi cumque, possimus commodi corporis illum.
      Delectus aut enim ipsa veritatis rem vero id eaque at nemo perferendis earum magnam adipisci possimus sed sapiente, magni esse amet modi! Quidem repellendus modi animi veniam provident molestias dolores.
      Dolorum quas commodi quam eos sint consectetur error fugiat culpa vel eligendi cum voluptatem officia expedita, laborum possimus nulla ratione suscipit delectus debitis! Totam suscipit reprehenderit adipisci illum praesentium doloribus?
      Odit dolorum veniam doloremque, ipsam maxime eveniet corporis cupiditate id rerum culpa consectetur recusandae laudantium accusantium assumenda ut. Voluptas praesentium maxime blanditiis numquam modi impedit fugit debitis ex, commodi natus!
      Distinctio, alias magnam ipsum ratione eius voluptatum amet ex non temporibus veniam sed, at deserunt nihil quia rerum beatae enim! Similique quasi harum dicta eos, recusandae error architecto non minima.
      Odit sunt, provident voluptate, minus blanditiis modi quis veniam, culpa error aspernatur illum soluta facere tempore voluptatem ea sint magnam natus repudiandae fugit saepe nostrum dignissimos doloremque maiores. Dolor, nesciunt!
      Reiciendis dolore possimus atque officia aliquam, a veritatis maxime eius earum ut dolorum aut, ullam facere molestiae impedit hic. Ex placeat sunt velit fugit enim hic nemo atque perspiciatis rerum.
      Eaque quas, incidunt blanditiis molestias unde perferendis? Deleniti omnis tempore quos, ab voluptate provident! Deserunt explicabo consequuntur modi earum? Aperiam explicabo velit vitae quas ut, autem nisi quam tenetur dolores?
      Minus ad vitae tempore. Nulla nesciunt illo quod quisquam error, vero ducimus repellat tempora blanditiis expedita ullam, optio iusto cum harum asperiores, quas temporibus. Soluta molestiae quod sed voluptatum maiores.
      Ipsam iure molestias, laborum culpa esse quos recusandae voluptatem. Numquam doloremque odio facilis repudiandae libero? Unde sequi omnis quasi nostrum accusamus velit expedita dolore a molestiae et! Praesentium, dolore laboriosam.
      Tempore eos dicta, quasi possimus veniam voluptate, consequatur repudiandae blanditiis sequi, delectus atque? Culpa odit explicabo animi nam sunt, molestiae repellat natus rerum dignissimos nesciunt, ipsum, fugiat maiores harum quis?
      Laudantium, enim exercitationem labore facere laboriosam cupiditate assumenda blanditiis modi ducimus non impedit ut et at vel! Ratione labore, soluta, sit in corrupti quos odio vero veritatis explicabo quibusdam distinctio!
      Sapiente velit sit quam, vero odit esse asperiores adipisci dolorem explicabo tenetur voluptatibus ratione at soluta magni sed delectus aliquam. Ipsam nulla tenetur velit quasi expedita maiores fugit quo aperiam?
      Asperiores maxime dolore deleniti accusamus obcaecati, eius optio non animi et aut molestiae ad eos quod minima mollitia soluta sunt magnam, sequi quos, blanditiis dolor reprehenderit labore praesentium nostrum. Vel.
      Adipisci repudiandae odio omnis quibusdam ex architecto, molestiae sapiente temporibus accusantium reprehenderit? Ipsa tempora alias facilis. Magni beatae, non reprehenderit, quis illo saepe quidem sunt iste, adipisci fugit blanditiis fuga.
      Ipsam ipsum esse recusandae earum exercitationem eum consectetur deleniti, animi eligendi repellendus quae, incidunt ab, dignissimos inventore. Recusandae minus officia ipsa dolor quas voluptatem fuga magni amet? Suscipit, corporis enim.
      Fugit id, beatae recusandae architecto cum excepturi incidunt facilis eos nobis, eligendi laborum numquam labore maxime quae, similique vitae! Neque voluptas quis beatae, reiciendis reprehenderit quidem amet delectus unde iste.
      Blanditiis accusantium similique quod autem totam vel? Dignissimos ab veniam illum qui animi cum et adipisci vel atque incidunt amet possimus, aliquam fuga aut labore sequi, architecto natus in impedit.
      Voluptatum excepturi doloribus facere tempora cumque veritatis eum praesentium! Voluptatum voluptatem sapiente quae et voluptas dicta vel nobis eius modi, consectetur animi sequi expedita non porro sunt ipsam libero. Eveniet.
      Quisquam alias maxime ipsa officia voluptas similique itaque vero non repellendus repellat magnam perspiciatis, illum quam officiis fuga laboriosam necessitatibus, architecto cum. Dolore amet, id cum accusantium labore consequatur aspernatur?
      Quasi eaque numquam facilis velit, quos praesentium illum asperiores esse distinctio hic maxime laborum impedit quam error voluptatibus libero deleniti veniam veritatis laboriosam illo pariatur aliquam aut non sequi. Veniam.
      Unde ipsum hic obcaecati est at laboriosam architecto exercitationem consectetur, perferendis dignissimos porro dolor quis molestiae sit praesentium dolore. Atque perferendis non nesciunt quos necessitatibus optio. Quas alias assumenda perferendis!
      Repudiandae laborum a ea soluta deserunt voluptatum repellendus hic non numquam, fugit ut deleniti at placeat molestias magni optio aut debitis, itaque quidem excepturi? Accusantium laborum repellendus tenetur harum nemo.
      Asperiores quo ut eligendi hic mollitia neque error exercitationem saepe iure itaque ullam, maxime alias quaerat. Provident fugit, cum doloribus repellat voluptatem excepturi eligendi nihil, eos ut aut, consequatur quia.
      Eveniet, placeat sit nemo omnis optio expedita suscipit autem impedit molestias maiores consequatur quo sed at tempore culpa deleniti porro odio! Quo sunt consectetur cumque atque veniam sit mollitia eius.
      Fugiat, corporis labore earum cumque natus officia sed sint. Doloremque commodi omnis amet vero impedit quia quibusdam! Incidunt corporis rerum suscipit veritatis laudantium doloremque, delectus, quibusdam impedit sed optio modi.
      Earum ullam quae fugiat, dicta repellendus velit beatae ea asperiores incidunt eius nobis magnam dolorem corrupti sit facilis similique eveniet recusandae enim saepe praesentium at! Nihil delectus expedita quo deserunt.
      Ullam fugiat obcaecati odit laudantium voluptatem molestiae dolores vero vel recusandae porro nesciunt voluptatum mollitia accusamus magnam rem ea soluta cupiditate, id accusantium atque, suscipit tempora omnis! Numquam, ipsum facilis?
      Assumenda, error modi. Id impedit atque corrupti rerum odio repudiandae minima ipsam. Quae quasi et quam tenetur perferendis magni nostrum deserunt modi officiis quidem sint earum officia, quia eveniet totam.
      Commodi quas omnis, ratione ad eos repudiandae soluta nobis dicta sequi provident ea nisi, laboriosam dolorem doloremque placeat, possimus neque repellendus voluptate tempore eaque quam delectus. Error rem aliquid nulla?
      Dicta eveniet eos vitae, sint facere sit laborum recusandae expedita aliquam, animi a corrupti repellendus eaque aperiam, aspernatur culpa tenetur ab aut et facilis! Accusamus explicabo ad aut doloremque asperiores.
      Reiciendis rerum quisquam quas? Recusandae, iusto fuga pariatur explicabo veritatis consequatur illo reprehenderit minus vitae eos sunt. Tempore, facilis, rerum magni maxime ea ab molestias quia vitae iure sapiente magnam?
      Odit asperiores illo nobis, voluptates deleniti corporis ex nam earum, rerum sed ea temporibus saepe exercitationem praesentium, placeat repellat! Tempore tenetur aut culpa libero, eius ut architecto vitae vero possimus?
      Impedit corporis at magnam delectus eius dicta dolorum repellendus repudiandae nostrum. Numquam tempore illo error labore impedit ratione sequi harum odio illum beatae, consectetur perferendis excepturi reiciendis possimus ut mollitia!
      Sed modi unde neque ratione, fuga blanditiis consectetur ut assumenda tenetur! Minus est assumenda pariatur sapiente. Commodi voluptate odio neque repellat sint qui. Voluptas magni quaerat nisi ad, deleniti amet.
      Unde eaque dolore quidem? Totam enim voluptates dolorem quos quis soluta et nulla est porro at minima nostrum ex, veniam esse minus blanditiis. Vitae ullam error sint eos autem magnam.
      Nobis quam cumque ab dicta ex tempore eos minus libero suscipit, in maxime animi non consequatur, provident quibusdam eaque sunt ut! Magnam, blanditiis officia. Nulla quo nemo quia quibusdam sequi?
      Illo quidem cumque vitae similique eligendi fuga dolores ipsam illum? Quidem, repudiandae molestias laboriosam a ab delectus beatae ipsa quia! Nihil asperiores labore repudiandae praesentium inventore commodi eos aperiam facere?
      Eveniet reprehenderit hic vero. Iste recusandae unde molestiae! Porro debitis illo sed eveniet impedit amet aspernatur, perspiciatis fugit! Atque illum repellat maiores accusantium perferendis porro asperiores, velit earum cupiditate corrupti!
      Adipisci ratione atque odit nesciunt voluptate ullam illo aspernatur voluptatum maiores! Fugiat velit harum sint consectetur, odit ipsa, aliquam, assumenda maxime ullam eum a. Dolores reprehenderit laudantium sapiente beatae esse?
      Quibusdam distinctio, pariatur veritatis maxime soluta ad cumque quam aliquid magni. Impedit ab culpa eos perferendis quasi iusto repellendus autem est tempore accusantium, consequuntur tempora placeat, vitae enim corporis labore.
      Maiores corrupti optio nobis inventore dolores magni ex explicabo ea reprehenderit delectus assumenda, numquam porro necessitatibus iusto saepe expedita quasi, quae fugit odio at quam cupiditate molestiae culpa. Illo, vel!
      Aspernatur aut, facilis assumenda ex ab voluptas neque at reiciendis quia pariatur veniam exercitationem sint, aliquam maiores quos. Ab amet unde consectetur! Dolorem natus illo blanditiis dolorum officiis fugiat hic!
      Officiis alias sed voluptates ut, possimus blanditiis nihil porro, placeat eveniet excepturi amet provident quisquam dicta accusamus aliquid! Obcaecati vel fuga itaque deleniti dolor inventore dolores sunt porro laboriosam aspernatur.
      Molestiae consectetur ipsa quam reiciendis quisquam obcaecati veniam eos sit, doloribus consequuntur excepturi aliquid, enim, fugiat id fugit! Incidunt culpa ea cum rem, ab delectus ad sint dignissimos laboriosam maiores.
      Eos maxime sunt voluptatibus ipsam possimus, quaerat alias amet velit fugiat repellendus! Tenetur suscipit illum magni asperiores facilis eius repellat temporibus. Possimus voluptas dignissimos veniam alias! Eius possimus quod quo.
      Hic minima, non, nostrum nam consequuntur maiores libero error culpa nisi totam beatae pariatur fugit explicabo architecto similique eveniet quisquam tenetur commodi! Facere suscipit officia eveniet. Quod enim eveniet asperiores.
      Quos, aliquam ad dignissimos vitae possimus tenetur ipsam? Architecto nesciunt facere blanditiis in asperiores porro sit vitae magnam earum qui nostrum eligendi voluptatum adipisci animi veniam minus sapiente, nobis laboriosam.
      Ex dolorum, sequi cum dolores non nobis atque? Excepturi neque, itaque ipsam quae doloremque distinctio ducimus? Optio, exercitationem quas adipisci reprehenderit minus, aliquam nobis quaerat illum similique dolorum consectetur sint!
      Aliquid non rerum possimus voluptates nulla fugit incidunt consequatur deserunt quia repellendus dolores impedit ullam atque, temporibus odio, eligendi ex id! Ab, consequuntur! Quas dolor, vero aliquam eius natus odio.
      Adipisci aperiam laudantium id optio numquam odit voluptas perferendis nulla accusantium harum autem, quos quaerat error repellat animi totam quo ipsa culpa est non tempora. Cum laborum exercitationem perspiciatis modi!
      Inventore praesentium blanditiis distinctio ea et ut ab. Veniam doloribus eveniet quis optio animi maiores esse, quo, at quod dolorum asperiores dicta sint? Distinctio est dolorum magni voluptates aspernatur quasi.
      Dicta minus deleniti excepturi culpa. Facere ab rerum necessitatibus doloribus est quaerat mollitia repudiandae recusandae quae perspiciatis, repellat laboriosam inventore. Cumque repellat esse consequatur illo veritatis culpa earum porro quibusdam.
      Inventore, soluta alias quasi at consequuntur fugiat consequatur harum ullam! Repellendus cupiditate necessitatibus, ea quasi voluptate deserunt fuga sapiente expedita deleniti possimus voluptas numquam incidunt debitis! Sed veniam omnis aperiam.
      Quas, unde? Expedita ut necessitatibus id rerum. Quidem praesentium harum ducimus exercitationem adipisci odio possimus provident vitae amet obcaecati iste quo blanditiis inventore, accusamus placeat laborum distinctio veniam vel. Nemo?
      Perferendis cupiditate dignissimos dolorum inventore omnis odit at adipisci vel? Explicabo quis voluptates repellendus aperiam voluptate sed enim vel provident, animi illum fuga, aliquam labore cupiditate, reiciendis hic in expedita.
      Adipisci veritatis aliquam soluta sint, aut eos ipsum esse neque alias nulla expedita consequatur voluptas magnam natus vel dicta inventore ab voluptatem accusantium voluptatum molestiae? Nulla veritatis consequatur libero asperiores.
      Amet itaque, totam labore culpa ipsum recusandae quia voluptates, non magni velit vitae, doloremque possimus nemo ea delectus fugiat consequuntur libero laborum obcaecati nisi. Earum vel voluptates sed hic sapiente.
      Unde dolore, suscipit omnis facere expedita quisquam ipsa beatae sint corrupti repellat veritatis adipisci fuga ex nulla, ullam modi inventore dolor deleniti recusandae consequuntur possimus saepe! Eveniet veniam repudiandae quos.
      Officiis quia, voluptates quod delectus, cupiditate sed illum quo molestias et numquam ut officia omnis id nobis doloremque autem ea harum quis. Sapiente, cumque quas temporibus nobis quo consequatur possimus.
      Quia, libero dolores aliquid voluptate eum quod fugiat aut quis nostrum eveniet nesciunt mollitia in numquam ab, corrupti veniam, quos ut aspernatur sed modi! At accusamus blanditiis sit voluptates voluptas?
      Et pariatur ad magni amet reprehenderit reiciendis voluptatibus, cumque minima minus molestias facilis, perspiciatis labore voluptatem ab iure autem. Sed incidunt necessitatibus tempora voluptate id facilis consequatur in dicta! Ea?
      Molestias, corporis accusamus. Molestiae enim, ullam ducimus laborum nesciunt facilis dolores explicabo corporis laudantium illum unde a aperiam quo culpa quisquam placeat ab ut aspernatur nisi, minima sit? Fugiat, soluta?
      Facilis est quidem, perspiciatis excepturi minima iste tempore nulla quaerat commodi error voluptas eius accusamus. Adipisci labore quod, non vel necessitatibus possimus exercitationem voluptates veniam soluta, voluptatem, ad esse magnam.
      Dolorum, dolores. Maiores, at nesciunt totam accusamus ducimus assumenda. Consequuntur iusto rerum quos laudantium dolor nemo necessitatibus tempora asperiores animi, voluptatem sapiente. Nostrum nobis esse officia modi pariatur quia quidem.
      Qui fuga architecto deserunt necessitatibus accusamus aliquam sint mollitia quia dicta nihil consequatur, error pariatur tenetur quas cumque ratione similique! Quo quae earum aliquid, maxime perspiciatis doloribus quis consequuntur atque.
      Et repellat ratione dolorum, dolores tempora temporibus laboriosam odit consequuntur veritatis quia, eos, minus labore omnis nobis numquam! Odit sit fugit animi quam. Qui animi eum, et in cupiditate nam!
      Amet, autem distinctio modi repellendus a voluptas, veritatis labore saepe deserunt id nostrum ipsum quaerat aut quo rerum delectus voluptate necessitatibus explicabo fuga provident soluta ea error possimus. Optio, maiores.
      Deserunt, repudiandae error quia ipsa blanditiis harum, quos amet sunt nesciunt ea accusantium? Aut dignissimos eius deleniti atque, obcaecati sapiente accusamus, maiores maxime porro quis minima perferendis, alias fuga similique.
      Recusandae, exercitationem. Officiis libero molestias doloremque eius impedit illum itaque, odio neque vitae debitis dolorum animi et error mollitia voluptate expedita autem similique deserunt cumque! Accusantium labore aspernatur ullam nemo.
      Obcaecati repellendus, illum alias autem soluta cum totam. Exercitationem vel facilis qui velit ea maxime suscipit perferendis? Perspiciatis molestiae illum, culpa ratione qui cum repellat. Quaerat repudiandae eius sint voluptatibus.
      Ex non nisi dolor corrupti velit, libero ipsam cumque placeat consectetur rerum accusamus cum, fuga quis ea sunt delectus natus vero enim similique vel inventore modi voluptatibus. Vero, magni assumenda?
      Esse nesciunt labore voluptas aliquam cumque, nemo, iusto tempore similique dolore non optio facilis! Error perspiciatis laboriosam illum sequi dolor perferendis distinctio tempora, quaerat recusandae, veritatis, velit consectetur dolorem temporibus.
      Molestias dolor qui inventore, esse similique cumque, ex repellat aliquid sunt quidem praesentium temporibus, voluptatem corporis ea nesciunt ducimus sint unde pariatur libero. Quas soluta quibusdam nobis reprehenderit ut esse!
      Quibusdam, expedita necessitatibus? Et dignissimos incidunt qui iste libero ipsam maxime quia sit totam, explicabo laborum temporibus reprehenderit placeat tempore repellat soluta ipsa ex neque vel voluptatibus suscipit numquam. Maiores.
      Repellat nisi, soluta reprehenderit, consectetur dicta magni eos in molestiae ut adipisci culpa sequi temporibus odit rerum aperiam. Harum officiis quod, perferendis explicabo exercitationem non? Dolores ad debitis itaque perferendis.
      Nobis, corrupti? Tempora quidem non quod dignissimos iure fugiat similique maiores alias. Dicta quaerat excepturi provident nostrum at mollitia repellendus ea ex quod? Maiores magni possimus odio ea sunt quia.
      Assumenda minus quo inventore nihil aliquam tenetur veniam iure vel omnis perspiciatis itaque voluptates vero voluptatum consectetur libero nulla, saepe, iste recusandae nam consequatur magnam excepturi enim! Dolorem, temporibus rerum?
      Iure incidunt tempore dolore, enim sapiente hic dolorum, qui quasi officiis laborum ex doloribus voluptates nostrum. Repudiandae tempore ea labore inventore sed, doloremque quaerat, commodi minus nam esse expedita sint?
      Doloribus distinctio cumque recusandae vero iste iure. Adipisci quia voluptas tempora accusamus sequi, eaque inventore minima optio mollitia repellat beatae blanditiis praesentium dolor, earum perspiciatis quidem. Accusantium ipsam veritatis necessitatibus.
      Esse accusantium fugiat sed! Atque corrupti animi hic sunt voluptas recusandae totam voluptates reiciendis rerum eos vel beatae a, doloribus repellendus vero quibusdam enim provident adipisci eveniet minima tempore facilis?
      Impedit porro optio esse, necessitatibus voluptate quibusdam voluptatem praesentium quia libero vero a consectetur veniam est aliquam quas vel id cupiditate tenetur, officia odit culpa sed quasi, modi odio. Praesentium.
      Odit necessitatibus ipsam optio consequatur iure maxime explicabo cupiditate et dolorem aliquam sapiente eaque, itaque nulla autem odio, provident praesentium possimus, vero reprehenderit quod magni sint dicta inventore incidunt! Magnam.
      Dolorum, quod animi. Cum dolorum ducimus sed odio fugiat alias neque earum? Corporis nisi architecto minus veritatis natus sequi aut beatae fuga sunt rem deserunt distinctio eveniet sit, voluptatum velit.
      Quasi illo necessitatibus ut harum molestiae animi, excepturi dolore exercitationem at hic officiis accusantium facilis quia magni sit nihil vel aut ratione error facere! Dolore cupiditate explicabo autem fugiat deserunt!
      Eos quis, iste est nobis repellat error quidem quia tenetur. Quibusdam corrupti nam eos nisi architecto aperiam doloribus ut odit assumenda fugit sunt, dolor adipisci atque repudiandae ad commodi necessitatibus!
      Vitae at velit itaque ad eos accusamus ea alias cum officia sequi dicta sapiente neque ex aliquam, dolorem dolore sint nulla illo! Maiores magni dolore, asperiores tempore perferendis debitis provident!
      Tempora, facilis! Reiciendis voluptate accusantium magni numquam animi ea doloribus dolores facilis enim non fugit voluptatibus expedita tempore, ipsam nesciunt ut odit nisi quae quis minima illum deserunt inventore molestias.
      Deleniti sint consequuntur perferendis cumque velit omnis dolores accusamus dicta suscipit laborum nam tempore ducimus commodi odio similique fuga itaque, quae aut rem illum animi quis. Totam reprehenderit qui assumenda?
      Maiores amet veritatis dolorem est qui quo non ipsam quos quam fugiat rem eum debitis eveniet impedit, dignissimos exercitationem temporibus eos esse ad! Quam excepturi cupiditate possimus tempore. Nam, eos?
      Distinctio velit fugit nihil ipsum assumenda facere recusandae sunt libero dicta mollitia porro quae adipisci, veniam quibusdam ea sequi commodi officia ex architecto eum est iste, odio ut? Quia, nulla.
      Molestiae a esse tempore, earum, quidem, necessitatibus saepe numquam adipisci impedit deleniti neque debitis explicabo! Nemo saepe quisquam illum ut perspiciatis! Expedita veniam accusamus odit nemo, maiores aperiam optio at?
      Corrupti sed error rem laborum consequuntur pariatur autem voluptate beatae? Itaque deserunt non fuga esse beatae deleniti quisquam, excepturi nemo, et officia cumque id minima ea maiores doloremque reiciendis hic.
      Numquam, quam aliquid atque deserunt ratione fuga nemo ducimus, possimus quasi ut exercitationem laudantium veniam eveniet harum officiis praesentium nihil illum. Sit recusandae illum consequatur, nulla harum fugit iste unde.
      Minus ratione architecto consequuntur odit eaque aliquam optio quo repellendus eius obcaecati eveniet magnam voluptatem, voluptatibus cumque iusto reprehenderit nostrum, amet excepturi! Iusto nesciunt ipsum debitis ipsam minus optio adipisci.
      Nisi quos, soluta incidunt, porro perferendis iure, cupiditate nihil voluptas beatae maiores possimus officia illo dolore officiis quidem? Nisi excepturi repellat tempore laboriosam quidem dolor delectus consequuntur consequatur non in.
      Natus ex fugit eos exercitationem voluptates possimus est aut similique voluptatum repudiandae harum saepe in doloribus molestiae nesciunt earum, eius eligendi eaque? Recusandae debitis fugiat deserunt, corporis nostrum itaque delectus.
        </div>
    </div>
  );
}
